const temp = () => {
  var iyziInit = {
    currency: "TRY",
    token: "aef389a1-7e0a-49cb-8114-f4c816cd2a16",
    price: 5.2,
    pwiPrice: 5.2,
    locale: "en",
    baseUrl: "https://sandbox-api.iyzipay.com",
    merchantGatewayBaseUrl: "https://sandbox-merchantgw.iyzipay.com",
    consumerGatewayBaseUrl: "https://sandbox-consumerapigw.iyzipay.com",
    registerCardEnabled: true,
    bkmEnabled: true,
    bankTransferEnabled: false,
    bankTransferTimeLimit: { value: 5, type: "day" },
    bankTransferRedirectUrl: "",
    bankTransferCustomUIProps: {},
    campaignEnabled: false,
    campaignMarketingUiDisplay: null,
    paymentSourceName: "zooz",
    plusInstallmentResponseList: null,
    payWithIyzicoSingleTab: false,
    payWithIyzicoSingleTabV2: false,
    payWithIyzicoOneTab: false,
    mixPaymentEnabled: true,
    creditCardEnabled: true,
    bankTransferAccounts: [],
    userCards: [],
    fundEnabled: true,
    memberCheckoutOtpData: {},
    force3Ds: false,
    isSandbox: true,
    storeNewCardEnabled: true,
    paymentWithNewCardEnabled: true,
    enabledApmTypes: ["SOFORT", "IDEAL", "QIWI", "GIROPAY"],
    payWithIyzicoUsed: false,
    payWithIyzicoEnabled: true,
    payWithIyzicoCustomUI: {},
    buyerName: "Higher",
    buyerSurname: "Faster",
    merchantInfo: "",
    merchantName: "Sandbox Merchant Name - 3403015",
    cancelUrl: "",
    buyerProtectionEnabled: false,
    hide3DS: false,
    gsmNumber: "+905555434332",
    email: "stronger@implementation.com",
    checkConsumerDetail: {},
    subscriptionPaymentEnabled: false,
    disabledCardStorageInfoCheckbox: false,
    ucsEnabled: false,
    fingerprintEnabled: false,
    payWithIyzicoFirstTab: false,
    creditEnabled: false,
    payWithIyzicoLead: false,
    zeroAuth: false,
    goBackUrl: "",
    quickPwiEnabled: false,
    quickPwiNewCardEnabled: false,
    consumerCardList: [],
    metadata: {},
  }; //{var iyziJSTag = document.createElement('script');iyziJSTag.setAttribute('src','https://sandbox-static.iyzipay.com/checkoutform/v2/bundle.js?v=1741215875529');document.head.appendChild(iyziJSTag);}};iyziInit.createTag();

  return (
    <>
      <script type='text/javascript'>
        if (typeof iyziInit == 'undefined') {}
      </script>
    </>
  );
};
